# Generated by Django 5.1.3 on 2024-12-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
